<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>agent_server</name>
  <version>0.0.0</version>
  <description>Ros2 Server used to connect orms_ui to the backend</description>
  <maintainer email="d.borghini3@studenti.unipi.it">dav</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>action_msgs</depend>
  <depend>agent_server_interfaces</depend>
  <depend>robothon_taskboard_msgs</depend>
  <depend>orms_lib_interfaces</depend>
  <depend>rosbridge_suite</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>